ism=input("ismnigizd kiriting")
print(f"salom{ism}")
son=float(input("yiligizni kiriting"))
mevalar=("olma""hurmo""gilos""olcha")
print(mevalar)
raqamlar=(2,4,5,6,9)
print(raqamlar)
davlatlar=('AQSH','ROSSIYA','ANGILYA','FRANSIYA')
print(davlatlar)
KITOBLAR=("SAROB""SOHIBQURON""UFQ""ODAM BO'LISH QIYIN""NUR BORKI SOYA BOR")
print(KITOBLAR)
juftsonlar=(12,14,16,18,20)
print(juftsonlar)
toqsonlar=(13,15,17,19)
print(toqsonlar)
unlihariflar=("a","e","i","o'","o","u")
print(unlihariflar)
fanlar=('matimatika','tapalogiya','diffrensiyal tenglma','matanaliz',)
print(fanlar)
a=input("sonni kiriting:")
a=input(a)
a=input("juft sonni kiriting")
a=input(a)
a=input("toq sonni kiriting")
a=input(a)
("ismingizni kiriting")
b=input(b)
input("hariflarni kiritng")
b=input(b)
son1=float(input("1-sonni kititing"))
son2=float(input("2-sonni kiriting"))
print(f"qo'shish:{son1+son2}")

son1=float(input("1-sonni kititing"))
son2=float(input("2-sonni kiriting"))
print(f"bo'lish:{son1-son2}")
son1=float(input("1-sonni kititing"))
son2=float(input("2-sonni kiriting"))
print(f"ko'paytrish:{son1*son2}")
sonlar=[1,2,3,4,5,6,]
b=sonlar.copy()
print(b)
isimlar=["adolat","nafosat","murot","hikmatoy"]
print(isimlar[2])
odamlar=["gullola","hasan","jasur","ruxshon","gulli","gulsanam","sevinch","shaxina","ro'zimurot","frdavs"]
odamlar.append("adolat")
print(odamlar)
odamlar=["gullola","hasan","jasur","ruxshon","gulli","gulsanam","sevinch","shaxina","ro'zimurot","frdavs"]
odamlar.pop(5)
print(odamlar)
odamlar=["gullola","hasan","jasur","ruxshon","gulli","gulsanam","sevinch","shaxina","ro'zimurot","frdavs"]
odamlar.insert(7,"nomoz")
print(odamlar)